CREATE TABLE IF NOT EXISTS DOCUMENT (
	DOC_ref				INTEGER PRIMARY KEY,
	DOC_name			TEXT NOT NULL,
	DOC_comment			TEXT NOT NULL,
	DOC_pdf  			BLOB NOT NULL,
	DOC_thumbnail		BLOB NOT NULL,
	DOC_creationDate	DATE NOT NULL,
	DOC_modDate			DATE NOT NULL
);