CREATE TABLE IF NOT EXISTS DOC_TAG (
	DOCTAG_ref				INTEGER PRIMARY KEY,
	DOC_ref 					INTEGER NOT NULL,
	TAG_ref 					INTEGER NOT NULL,
	DOCTAG_creationDate		DATE NOT NULL,
	DOCTAG_modDate			DATE NOT NULL,
	FOREIGN KEY (DOC_ref) references DOCUMENT (DOC_ref) ON DELETE CASCADE,
	FOREIGN KEY (TAG_ref) references TAG (TAG_ref) ON DELETE CASCADE
);