//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Athena.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Athena.Resources.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new tag.
        /// </summary>
        public static string AddNewTag {
            get {
                return ResourceManager.GetString("AddNewTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the new tag (max. 20 characters).
        /// </summary>
        public static string AddNewTagName {
            get {
                return ResourceManager.GetString("AddNewTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to change the language to {0}?.
        /// </summary>
        public static string ChangeLanguageConfirm {
            get {
                return ResourceManager.GetString("ChangeLanguageConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change name.
        /// </summary>
        public static string ChangeName {
            get {
                return ResourceManager.GetString("ChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete document.
        /// </summary>
        public static string DeleteDocument {
            get {
                return ResourceManager.GetString("DeleteDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the document {0}?
        ///The document cannot be recovered!.
        /// </summary>
        public static string DeleteDocumentConfirm {
            get {
                return ResourceManager.GetString("DeleteDocumentConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete folder.
        /// </summary>
        public static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the folder {0}?
        ///The folder cannot be recovered!.
        /// </summary>
        public static string DeleteFolderConfirm {
            get {
                return ResourceManager.GetString("DeleteFolderConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete page.
        /// </summary>
        public static string DeletePage {
            get {
                return ResourceManager.GetString("DeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the page {0}?
        ///The page cannot be recovered!.
        /// </summary>
        public static string DeletePageConfirm {
            get {
                return ResourceManager.GetString("DeletePageConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete tag.
        /// </summary>
        public static string DeleteTag {
            get {
                return ResourceManager.GetString("DeleteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the tag {0}?
        ///The tag cannot be recovered!.
        /// </summary>
        public static string DeleteTagConfirm {
            get {
                return ResourceManager.GetString("DeleteTagConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted document {0}.
        /// </summary>
        public static string DocumentDeleted {
            get {
                return ResourceManager.GetString("DocumentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this document....
        /// </summary>
        public static string DocumentDetailsDocumentInfo {
            get {
                return ResourceManager.GetString("DocumentDetailsDocumentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with external application.
        /// </summary>
        public static string DocumentDetailsOpenWithExt {
            get {
                return ResourceManager.GetString("DocumentDetailsOpenWithExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add additional information.
        /// </summary>
        public static string DocumentEditorAddAdditionalInformation {
            get {
                return ResourceManager.GetString("DocumentEditorAddAdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add documents.
        /// </summary>
        public static string DocumentEditorAddDocuments {
            get {
                return ResourceManager.GetString("DocumentEditorAddDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athena uses advanced artifical intelligence (AI) technology to detect text within documents, allowing you to efficiently search for any words across all documents.
        ///Depending on the size of the documents, this process may take a moment..
        /// </summary>
        public static string DocumentEditorAIDescription {
            get {
                return ResourceManager.GetString("DocumentEditorAIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI text detection.
        /// </summary>
        public static string DocumentEditorAIHeader {
            get {
                return ResourceManager.GetString("DocumentEditorAIHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable AI text detection.
        /// </summary>
        public static string DocumentEditorEnableAI {
            get {
                return ResourceManager.GetString("DocumentEditorEnableAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan a document with your camera, choose one from your gallery or pick a document from your device.
        /// </summary>
        public static string DocumentEditorLoadDocument {
            get {
                return ResourceManager.GetString("DocumentEditorLoadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags available. Use the tags tab to add new tags.
        /// </summary>
        public static string DocumentEditorNoTags {
            get {
                return ResourceManager.GetString("DocumentEditorNoTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tags.
        /// </summary>
        public static string DocumentEditorSelectTags {
            get {
                return ResourceManager.GetString("DocumentEditorSelectTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the plus button to add a new document.
        /// </summary>
        public static string DocumentEmpty {
            get {
                return ResourceManager.GetString("DocumentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document {0} successfully moved to {1}.
        /// </summary>
        public static string DocumentMovedSuccessfully {
            get {
                return ResourceManager.GetString("DocumentMovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional comment.
        /// </summary>
        public static string DocumentVMComment {
            get {
                return ResourceManager.GetString("DocumentVMComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment should not exceed 80 characters.
        /// </summary>
        public static string DocumentVMCommentExceedsCharLimit {
            get {
                return ResourceManager.GetString("DocumentVMCommentExceedsCharLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document name.
        /// </summary>
        public static string DocumentVMName {
            get {
                return ResourceManager.GetString("DocumentVMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name should not exceed 45 characters.
        /// </summary>
        public static string DocumentVMNameCharsExceedLimit {
            get {
                return ResourceManager.GetString("DocumentVMNameCharsExceedLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string DocumentVMNameRequired {
            get {
                return ResourceManager.GetString("DocumentVMNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit document.
        /// </summary>
        public static string EditDocument {
            get {
                return ResourceManager.GetString("EditDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit tag.
        /// </summary>
        public static string EditTag {
            get {
                return ResourceManager.GetString("EditTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted folder {0}.
        /// </summary>
        public static string FolderDeleted {
            get {
                return ResourceManager.GetString("FolderDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the plus button to add a new folder.
        /// </summary>
        public static string FolderEmpty {
            get {
                return ResourceManager.GetString("FolderEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this folder....
        /// </summary>
        public static string FolderInformation {
            get {
                return ResourceManager.GetString("FolderInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional comment.
        /// </summary>
        public static string FolderVMComment {
            get {
                return ResourceManager.GetString("FolderVMComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment should not exceed 80 characters.
        /// </summary>
        public static string FolderVMCommentExceedCharLimit {
            get {
                return ResourceManager.GetString("FolderVMCommentExceedCharLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder name.
        /// </summary>
        public static string FolderVMName {
            get {
                return ResourceManager.GetString("FolderVMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name should not exceed 45 characters.
        /// </summary>
        public static string FolderVMTitleExceedCharLimit {
            get {
                return ResourceManager.GetString("FolderVMTitleExceedCharLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string FolderVMTitleRequired {
            get {
                return ResourceManager.GetString("FolderVMTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading documents....
        /// </summary>
        public static string LoadingDocuments {
            get {
                return ResourceManager.GetString("LoadingDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading pages....
        /// </summary>
        public static string LoadingPages {
            get {
                return ResourceManager.GetString("LoadingPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move document.
        /// </summary>
        public static string MoveDocument {
            get {
                return ResourceManager.GetString("MoveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to move the document {0} to page {1}?.
        /// </summary>
        public static string MoveDocumentConfirm {
            get {
                return ResourceManager.GetString("MoveDocumentConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to selected page.
        /// </summary>
        public static string MoveToSelectedPage {
            get {
                return ResourceManager.GetString("MoveToSelectedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Planned features&lt;/h2&gt;
        ///&lt;p&gt;- Remove pages and allow nesting of folders&lt;/p&gt;
        ///&lt;p&gt;- Allow adding documents to folders&lt;/p&gt;
        ///&lt;p&gt;- Export and import data&lt;/p&gt;
        ///&lt;p&gt;- Encrypt stored documents&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///
        ///&lt;h2&gt;Changelog&lt;/h2&gt;
        ///&lt;p&gt;Information about fixes, new features and improvements.&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///
        ///&lt;h3&gt;Athena v1.0.5 (06.17.2024)&lt;/h3&gt;
        ///&lt;p&gt;- Fix issues when adding tags &lt;/p&gt;
        ///&lt;p&gt;- Activate ads&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///
        ///&lt;h3&gt;Athena v1.0.4 (06.12.2024)&lt;/h3&gt;
        ///&lt;p&gt;- Improve performance&lt;/p&gt;
        ///&lt;p&gt;- Update dependen [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NewsText {
            get {
                return ResourceManager.GetString("NewsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tag.
        /// </summary>
        public static string NewTag {
            get {
                return ResourceManager.GetString("NewTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted page {0}.
        /// </summary>
        public static string PageDeleted {
            get {
                return ResourceManager.GetString("PageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the plus button to add a new page.
        /// </summary>
        public static string PageEmpty {
            get {
                return ResourceManager.GetString("PageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this page....
        /// </summary>
        public static string PageInformation {
            get {
                return ResourceManager.GetString("PageInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional comment.
        /// </summary>
        public static string PageVMComment {
            get {
                return ResourceManager.GetString("PageVMComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment should not exceed 80 characters.
        /// </summary>
        public static string PageVMCommentExceedCharLimit {
            get {
                return ResourceManager.GetString("PageVMCommentExceedCharLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page title.
        /// </summary>
        public static string PageVMTitle {
            get {
                return ResourceManager.GetString("PageVMTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title should not exceed 45 characters.
        /// </summary>
        public static string PageVMTitleExceedCharLimit {
            get {
                return ResourceManager.GetString("PageVMTitleExceedCharLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required.
        /// </summary>
        public static string PageVMTitleRequired {
            get {
                return ResourceManager.GetString("PageVMTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search filter.
        /// </summary>
        public static string SearchFilter {
            get {
                return ResourceManager.GetString("SearchFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full text search.
        /// </summary>
        public static string SearchFullTextSearch {
            get {
                return ResourceManager.GetString("SearchFullTextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full text search is enabled. It may take longer to find all results.
        /// </summary>
        public static string SearchFullTextSearchEnabled {
            get {
                return ResourceManager.GetString("SearchFullTextSearchEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        public static string SearchNoResults {
            get {
                return ResourceManager.GetString("SearchNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only show documents with selected tags.
        /// </summary>
        public static string SearchOnlyWithSelectedTags {
            get {
                return ResourceManager.GetString("SearchOnlyWithSelectedTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for document name or text....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document: .
        /// </summary>
        public static string SearchResultDocument {
            get {
                return ResourceManager.GetString("SearchResultDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder: .
        /// </summary>
        public static string SearchResultFolder {
            get {
                return ResourceManager.GetString("SearchResultFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page: .
        /// </summary>
        public static string SearchResultPage {
            get {
                return ResourceManager.GetString("SearchResultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string SearchRunning {
            get {
                return ResourceManager.GetString("SearchRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tutorial.
        /// </summary>
        public static string ShowTutorial {
            get {
                return ResourceManager.GetString("ShowTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start searching.
        /// </summary>
        public static string StartSearch {
            get {
                return ResourceManager.GetString("StartSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted tag {0}.
        /// </summary>
        public static string TagDeleted {
            get {
                return ResourceManager.GetString("TagDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the plus button to add a new tag.
        /// </summary>
        public static string TagEmpty {
            get {
                return ResourceManager.GetString("TagEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a new name for {0}.
        /// </summary>
        public static string TagNewName {
            get {
                return ResourceManager.GetString("TagNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags saved successfully.
        /// </summary>
        public static string TagsSavedSuccessfully {
            get {
                return ResourceManager.GetString("TagsSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start page contains your folders..
        /// </summary>
        public static string TutStep1 {
            get {
                return ResourceManager.GetString("TutStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the three dots for more options..
        /// </summary>
        public static string TutStep10 {
            get {
                return ResourceManager.GetString("TutStep10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the search tab, you can look for documents by name or by specific text within them. For example, searching for a document titled &apos;Contract&apos; produces one result..
        /// </summary>
        public static string TutStep11 {
            get {
                return ResourceManager.GetString("TutStep11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By using the filter icon, you can set specific search conditions. 
        ///You can filter results by tags or enable full text search, but only documents created with the &apos;Enable AI text detection&apos; feature are included in the full text search..
        /// </summary>
        public static string TutStep12 {
            get {
                return ResourceManager.GetString("TutStep12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this example, the full text search filter is activated. Searching for the word &apos;Amet&apos; yields one result because the document &apos;Contract&apos; contains the word &apos;Amet&apos;..
        /// </summary>
        public static string TutStep13 {
            get {
                return ResourceManager.GetString("TutStep13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-tapping on a folder offers you a menu to quickly manage a folder..
        /// </summary>
        public static string TutStep2 {
            get {
                return ResourceManager.GetString("TutStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add pages using the plus button. 
        ///Use the three dots to access the folder menu. 
        ///Long-pressing a page opens a menu for managing that page..
        /// </summary>
        public static string TutStep3 {
            get {
                return ResourceManager.GetString("TutStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add documents using the plus button. 
        ///Use the three dots to access the page menu.
        ///Long-pressing a document opens a menu for managing that document..
        /// </summary>
        public static string TutStep4 {
            get {
                return ResourceManager.GetString("TutStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a document, simply scan images with your camera, select them from your gallery or choose PDFs on your device.
        ///In the end, they are all merged into a single PDF..
        /// </summary>
        public static string TutStep5 {
            get {
                return ResourceManager.GetString("TutStep5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the &apos;Delete document&apos; button to remove document from the selection.
        ///Use the &apos;Enable AI text detection&apos; feature to scan the documents and make the text searchable..
        /// </summary>
        public static string TutStep6 {
            get {
                return ResourceManager.GetString("TutStep6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For each document, you can choose a title and an optional comment.
        ///You can also select tags to categorize the documents. 
        ///Use the Tags tab to manage the tags..
        /// </summary>
        public static string TutStep7 {
            get {
                return ResourceManager.GetString("TutStep7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After selecting an image, you can optionally crop it..
        /// </summary>
        public static string TutStep8 {
            get {
                return ResourceManager.GetString("TutStep8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long pressing a folder, a page or a document opens a menu to manage the resource..
        /// </summary>
        public static string TutStep9 {
            get {
                return ResourceManager.GetString("TutStep9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for downloading the Athena: AI Document Manager app!
        ///A short tutorial follows to show you the basics
        ///
        ///You can repeat this tutorial anytime via the &apos;Show tutorial&apos; button in the Settings tab..
        /// </summary>
        public static string TutWelcome {
            get {
                return ResourceManager.GetString("TutWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
