//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Athena.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Athena.Resources.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New document.
        /// </summary>
        public static string AddDocument {
            get {
                return ResourceManager.GetString("AddDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new tag.
        /// </summary>
        public static string AddNewTag {
            get {
                return ResourceManager.GetString("AddNewTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the new tag (max. 20 characters).
        /// </summary>
        public static string AddNewTagName {
            get {
                return ResourceManager.GetString("AddNewTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to change the language to {0}?.
        /// </summary>
        public static string ChangeLanguageConfirm {
            get {
                return ResourceManager.GetString("ChangeLanguageConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change name.
        /// </summary>
        public static string ChangeName {
            get {
                return ResourceManager.GetString("ChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete document.
        /// </summary>
        public static string DeleteDocument {
            get {
                return ResourceManager.GetString("DeleteDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the document {0}?
        ///The document cannot be recovered!.
        /// </summary>
        public static string DeleteDocumentConfirm {
            get {
                return ResourceManager.GetString("DeleteDocumentConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete folder.
        /// </summary>
        public static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the folder {0}?
        ///The folder cannot be recovered!.
        /// </summary>
        public static string DeleteFolderConfirm {
            get {
                return ResourceManager.GetString("DeleteFolderConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete page.
        /// </summary>
        public static string DeletePage {
            get {
                return ResourceManager.GetString("DeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the page {0}?
        ///The page cannot be recovered!.
        /// </summary>
        public static string DeletePageConfirm {
            get {
                return ResourceManager.GetString("DeletePageConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete tag.
        /// </summary>
        public static string DeleteTag {
            get {
                return ResourceManager.GetString("DeleteTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the tag {0}?
        ///The tag cannot be recovered!.
        /// </summary>
        public static string DeleteTagConfirm {
            get {
                return ResourceManager.GetString("DeleteTagConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You created &lt;strong&gt;{0}&lt;/strong&gt; {1} and &lt;strong&gt;{2}&lt;/strong&gt; {3}.
        /// </summary>
        public static string DocFolderOverviewText {
            get {
                return ResourceManager.GetString("DocFolderOverviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated at {0}.
        /// </summary>
        public static string DocFolderOverviewTextLastUpdate {
            get {
                return ResourceManager.GetString("DocFolderOverviewTextLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted document {0}.
        /// </summary>
        public static string DocumentDeleted {
            get {
                return ResourceManager.GetString("DocumentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this document....
        /// </summary>
        public static string DocumentDetailsDocumentInfo {
            get {
                return ResourceManager.GetString("DocumentDetailsDocumentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with external application.
        /// </summary>
        public static string DocumentDetailsOpenWithExt {
            get {
                return ResourceManager.GetString("DocumentDetailsOpenWithExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add additional information.
        /// </summary>
        public static string DocumentEditorAddAdditionalInformation {
            get {
                return ResourceManager.GetString("DocumentEditorAddAdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add documents.
        /// </summary>
        public static string DocumentEditorAddDocuments {
            get {
                return ResourceManager.GetString("DocumentEditorAddDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Athena uses advanced artifical intelligence (AI) technology to detect text within documents, allowing you to efficiently search for any words across all documents.
        ///Depending on the size of the documents, this process may take a moment..
        /// </summary>
        public static string DocumentEditorAIDescription {
            get {
                return ResourceManager.GetString("DocumentEditorAIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI text detection.
        /// </summary>
        public static string DocumentEditorAIHeader {
            get {
                return ResourceManager.GetString("DocumentEditorAIHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect text in documents.
        /// </summary>
        public static string DocumentEditorEnableAI {
            get {
                return ResourceManager.GetString("DocumentEditorEnableAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan a document with your camera, choose one from your gallery or pick a document from your device.
        /// </summary>
        public static string DocumentEditorLoadDocument {
            get {
                return ResourceManager.GetString("DocumentEditorLoadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags available. Use the tags tab to add new tags.
        /// </summary>
        public static string DocumentEditorNoTags {
            get {
                return ResourceManager.GetString("DocumentEditorNoTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tags.
        /// </summary>
        public static string DocumentEditorSelectTags {
            get {
                return ResourceManager.GetString("DocumentEditorSelectTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the plus button to add a new document.
        /// </summary>
        public static string DocumentEmpty {
            get {
                return ResourceManager.GetString("DocumentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document {0} successfully moved to {1}.
        /// </summary>
        public static string DocumentMovedSuccessfully {
            get {
                return ResourceManager.GetString("DocumentMovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional comment.
        /// </summary>
        public static string DocumentVMComment {
            get {
                return ResourceManager.GetString("DocumentVMComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment should not exceed 80 characters.
        /// </summary>
        public static string DocumentVMCommentExceedsCharLimit {
            get {
                return ResourceManager.GetString("DocumentVMCommentExceedsCharLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document name.
        /// </summary>
        public static string DocumentVMName {
            get {
                return ResourceManager.GetString("DocumentVMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name should not exceed 45 characters.
        /// </summary>
        public static string DocumentVMNameCharsExceedLimit {
            get {
                return ResourceManager.GetString("DocumentVMNameCharsExceedLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string DocumentVMNameRequired {
            get {
                return ResourceManager.GetString("DocumentVMNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit document.
        /// </summary>
        public static string EditDocument {
            get {
                return ResourceManager.GetString("EditDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit tag.
        /// </summary>
        public static string EditTag {
            get {
                return ResourceManager.GetString("EditTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders and documents.
        /// </summary>
        public static string FolderAndDocuments {
            get {
                return ResourceManager.GetString("FolderAndDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted folder {0}.
        /// </summary>
        public static string FolderDeleted {
            get {
                return ResourceManager.GetString("FolderDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the plus button to add a new folder or a new document.
        /// </summary>
        public static string FolderEmpty {
            get {
                return ResourceManager.GetString("FolderEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this folder....
        /// </summary>
        public static string FolderInformation {
            get {
                return ResourceManager.GetString("FolderInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional comment.
        /// </summary>
        public static string FolderVMComment {
            get {
                return ResourceManager.GetString("FolderVMComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment should not exceed 80 characters.
        /// </summary>
        public static string FolderVMCommentExceedCharLimit {
            get {
                return ResourceManager.GetString("FolderVMCommentExceedCharLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder name.
        /// </summary>
        public static string FolderVMName {
            get {
                return ResourceManager.GetString("FolderVMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name should not exceed 45 characters.
        /// </summary>
        public static string FolderVMTitleExceedCharLimit {
            get {
                return ResourceManager.GetString("FolderVMTitleExceedCharLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string FolderVMTitleRequired {
            get {
                return ResourceManager.GetString("FolderVMTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good afternoon.
        /// </summary>
        public static string GoodAfternoon {
            get {
                return ResourceManager.GetString("GoodAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good evening.
        /// </summary>
        public static string GoodEvening {
            get {
                return ResourceManager.GetString("GoodEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good morning.
        /// </summary>
        public static string GoodMorning {
            get {
                return ResourceManager.GetString("GoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string GoodNight {
            get {
                return ResourceManager.GetString("GoodNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading documents....
        /// </summary>
        public static string LoadingDocuments {
            get {
                return ResourceManager.GetString("LoadingDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading pages....
        /// </summary>
        public static string LoadingPages {
            get {
                return ResourceManager.GetString("LoadingPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move document.
        /// </summary>
        public static string MoveDocument {
            get {
                return ResourceManager.GetString("MoveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to move the document {0} to page {1}?.
        /// </summary>
        public static string MoveDocumentConfirm {
            get {
                return ResourceManager.GetString("MoveDocumentConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to selected page.
        /// </summary>
        public static string MoveToSelectedPage {
            get {
                return ResourceManager.GetString("MoveToSelectedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tag.
        /// </summary>
        public static string NewTag {
            get {
                return ResourceManager.GetString("NewTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recent documents.
        /// </summary>
        public static string NoRecentDocuments {
            get {
                return ResourceManager.GetString("NoRecentDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in browser.
        /// </summary>
        public static string OpenInBrowser {
            get {
                return ResourceManager.GetString("OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent documents.
        /// </summary>
        public static string RecentDocuments {
            get {
                return ResourceManager.GetString("RecentDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search filter.
        /// </summary>
        public static string SearchFilter {
            get {
                return ResourceManager.GetString("SearchFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full text search.
        /// </summary>
        public static string SearchFullTextSearch {
            get {
                return ResourceManager.GetString("SearchFullTextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full text search is enabled. It may take longer to find all results.
        /// </summary>
        public static string SearchFullTextSearchEnabled {
            get {
                return ResourceManager.GetString("SearchFullTextSearchEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        public static string SearchNoResults {
            get {
                return ResourceManager.GetString("SearchNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only show documents with selected tags.
        /// </summary>
        public static string SearchOnlyWithSelectedTags {
            get {
                return ResourceManager.GetString("SearchOnlyWithSelectedTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for document name or text....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document: .
        /// </summary>
        public static string SearchResultDocument {
            get {
                return ResourceManager.GetString("SearchResultDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder: .
        /// </summary>
        public static string SearchResultFolder {
            get {
                return ResourceManager.GetString("SearchResultFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page: .
        /// </summary>
        public static string SearchResultPage {
            get {
                return ResourceManager.GetString("SearchResultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string SearchRunning {
            get {
                return ResourceManager.GetString("SearchRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright related information about third-party resources.
        /// </summary>
        public static string SettingsCopyrightDesc {
            get {
                return ResourceManager.GetString("SettingsCopyrightDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string SettingsCopyrightTitle {
            get {
                return ResourceManager.GetString("SettingsCopyrightTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report bugs, request features or provide general feedback.
        /// </summary>
        public static string SettingsFeedbackDesc {
            get {
                return ResourceManager.GetString("SettingsFeedbackDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string SettingsFeedbackTitle {
            get {
                return ResourceManager.GetString("SettingsFeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information, explanations and further help.
        /// </summary>
        public static string SettingsHelpDesc {
            get {
                return ResourceManager.GetString("SettingsHelpDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string SettingsHelpTitle {
            get {
                return ResourceManager.GetString("SettingsHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News and updates about the app.
        /// </summary>
        public static string SettingsNewsDesc {
            get {
                return ResourceManager.GetString("SettingsNewsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string SettingsNewsTitle {
            get {
                return ResourceManager.GetString("SettingsNewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal information about Privacy policy.
        /// </summary>
        public static string SettingsPrivacyPolicyDesc {
            get {
                return ResourceManager.GetString("SettingsPrivacyPolicyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string SettingsPrivacyPolicyTitle {
            get {
                return ResourceManager.GetString("SettingsPrivacyPolicyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal information about Terms and Conditions.
        /// </summary>
        public static string SettingsTermsOfUseDesc {
            get {
                return ResourceManager.GetString("SettingsTermsOfUseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        public static string SettingsTermsOfUseTitle {
            get {
                return ResourceManager.GetString("SettingsTermsOfUseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tutorial.
        /// </summary>
        public static string ShowTutorial {
            get {
                return ResourceManager.GetString("ShowTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start searching.
        /// </summary>
        public static string StartSearch {
            get {
                return ResourceManager.GetString("StartSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted tag {0}.
        /// </summary>
        public static string TagDeleted {
            get {
                return ResourceManager.GetString("TagDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the plus button to add a new tag.
        /// </summary>
        public static string TagEmpty {
            get {
                return ResourceManager.GetString("TagEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name.
        /// </summary>
        public static string TagName {
            get {
                return ResourceManager.GetString("TagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a new name for {0}.
        /// </summary>
        public static string TagNewName {
            get {
                return ResourceManager.GetString("TagNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags saved successfully.
        /// </summary>
        public static string TagsSavedSuccessfully {
            get {
                return ResourceManager.GetString("TagsSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color.
        /// </summary>
        public static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name.
        /// </summary>
        public static string WelcomeEnterName {
            get {
                return ResourceManager.GetString("WelcomeEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name will only be used for a personal greeting.
        /// </summary>
        public static string WelcomeEnterNameDesc {
            get {
                return ResourceManager.GetString("WelcomeEnterNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now ready to use Athena!.
        /// </summary>
        public static string WelcomeReady {
            get {
                return ResourceManager.GetString("WelcomeReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions or feedback, you can contact us at any time via the feedback form in the settings.
        /// </summary>
        public static string WelcomeReadyDesc {
            get {
                return ResourceManager.GetString("WelcomeReadyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your language.
        /// </summary>
        public static string WelcomeSelectLanguage {
            get {
                return ResourceManager.GetString("WelcomeSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for downloading the Athena: AI Document Manager app!.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string WelcomeYourNamePlaceholder {
            get {
                return ResourceManager.GetString("WelcomeYourNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
