CREATE TABLE IF NOT EXISTS PAGE_TAG (
	PGTAG_REF				INTEGER PRIMARY KEY,
	PG_ref 					INTEGER NOT NULL,
	TAG_ref 					INTEGER NOT NULL,
	PGTAG_creationDate		DATE NOT NULL,
	PGTAG_modDate			DATE NOT NULL,
	FOREIGN KEY (TAG_ref) references TAG (TAG_ref) ON DELETE CASCADE,
	FOREIGN KEY (PG_ref) references PAGE (PG_ref) ON DELETE CASCADE
);