CREATE TABLE IF NOT EXISTS PAGE_DOC (
	PGDOC_REF				INTEGER PRIMARY KEY,
	PG_ref 					INTEGER NOT NULL,
	DOC_ref 					INTEGER NOT NULL,
	PGDOC_creationDate		DATE NOT NULL,
	PGDOC_modDate			DATE NOT NULL,
	FOREIGN KEY (DOC_ref) references DOCUMENT (DOC_ref) ON DELETE CASCADE,
	FOREIGN KEY (PG_ref) references PAGE (PG_ref) ON DELETE CASCADE
);