using System.Collections.ObjectModel;
using Athena.DataModel;
using Athena.DataModel.Core;
using Athena.Resources.Localization;
using CommunityToolkit.Maui.Alerts;
using CommunityToolkit.Maui.Core;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Syncfusion.Maui.Popup;

namespace Athena.UI
{
    public partial class TagsOverviewViewModel : ContextViewModel
    {
        [ObservableProperty]
        private VisualCollection<TagViewModel, Tag> _tags;

        [ObservableProperty]
        private ObservableCollection<ColorViewModel> _predefinedColors;

        [ObservableProperty]
        private ColorViewModel _selectedBackgroundColor;

        [ObservableProperty]
        private ColorViewModel _selectedTextColor;

        [ObservableProperty]
        private string _selectedTagName;

        [ObservableProperty]
        private bool _isEditPopupOpen;

        [ObservableProperty]
        private PopupButtonAppearanceMode _appearanceMode;

        [ObservableProperty]
        private TagViewModel _selectedTag;

        [ObservableProperty]
        private bool _tagsAvailable;

        private static readonly int BlackIndex = 0;
        private static readonly int WhiteIndex = 1;

        public TagsOverviewViewModel()
        {
            // Autogenerated.
            PredefinedColors = new() {
                new ColorViewModel("Black", Colors.Black.ToHex()),
                new ColorViewModel("White", Colors.White.ToHex()),
                new ColorViewModel("Red", Colors.IndianRed.ToHex()),
                new ColorViewModel("Blue", Colors.Blue.ToHex()),
                new ColorViewModel("Green", Colors.Green.ToHex()),
                new ColorViewModel("Yellow", Colors.Yellow.ToHex()),
            };
        }

        public override async Task InitializeAsync()
        {
            List<Tag> allTags = null;

            await ExecuteBackgroundAction(context =>
            {
                allTags = Tag.ReadAll(context).ToList();
            });

            if (allTags.Count == 0)
            {
                Tags = new();
            }
            else
            {
                Tags = new(allTags.Select(x => new TagViewModel(x)));
            }

            TagsAvailable = Tags.Count > 0;
        }

        [RelayCommand]
        public void TagSelected(TagViewModel tag)
        {
            if (tag == null)
                return;

            AppearanceMode = PopupButtonAppearanceMode.TwoButton;
            SelectedTag = tag;

            ColorViewModel bgColor = PredefinedColors.FirstOrDefault(
                x => x.Hex.Equals(SelectedTag.BackgroundColor, StringComparison.OrdinalIgnoreCase));

            bgColor ??= PredefinedColors[WhiteIndex];

            ColorViewModel textColor = PredefinedColors.FirstOrDefault(
                x => x.Hex.Equals(SelectedTag.TextColor, StringComparison.OrdinalIgnoreCase));

            textColor ??= PredefinedColors[BlackIndex];

            SelectedBackgroundColor = bgColor;
            SelectedTextColor = textColor;
            SelectedTagName = SelectedTag.Name;

            IsEditPopupOpen = true;
        }

        [RelayCommand]
        internal void AddNewTag()
        {
            AppearanceMode = PopupButtonAppearanceMode.OneButton;
            Tag newTag = new Tag();
            SelectedTag = new TagViewModel(newTag);
            SelectedBackgroundColor = PredefinedColors[WhiteIndex];
            SelectedTextColor = PredefinedColors[BlackIndex];
            SelectedTagName = string.Empty;

            IsEditPopupOpen = true;
        }

        [RelayCommand]
        public async Task SaveSelectedTag()
        {
            if (SelectedTag == null)
                return;

            if (string.IsNullOrEmpty(SelectedTagName))
            {
                await Toast.Make(Localization.TagNameCannotBeEmpty, ToastDuration.Long).Show();
                SelectedTag = null;
                IsEditPopupOpen = false;
                return;
            }

            bool isNew = SelectedTag.Id == IntegerEntityKey.TemporaryId;

            IContext context = RetrieveContext();

            SelectedTag.Name = SelectedTagName;
            SelectedTag.BackgroundColor = SelectedBackgroundColor.Hex;
            SelectedTag.TextColor = SelectedTextColor.Hex;

            SelectedTag.Save(context);

            if (isNew)
            {
                Tags.Add(SelectedTag);
                TagsAvailable = true;
            }

            SelectedTag = null;
            IsEditPopupOpen = false;
        }

        [RelayCommand]
        public async Task DeleteSelectedTag()
        {
            if (SelectedTag == null)
                return;

            if (SelectedTag.Id == IntegerEntityKey.TemporaryId)
                return;

            bool delete = await DisplayAlert(
                    Localization.DeleteTag,
                    string.Format(Localization.DeleteTagConfirm, SelectedTag.Name),
                    Localization.Yes,
                    Localization.No);

            IContext context = RetrieveContext();

            if (delete)
            {
                SelectedTag.Delete(context);
                Tags.Remove(SelectedTag);
                TagsAvailable = Tags.Count > 0;
                await Toast.Make(string.Format(Localization.TagDeleted, SelectedTag.Name), ToastDuration.Long).Show();
            }

            SelectedTag = null;
            IsEditPopupOpen = false;
        }
    }
}
