CREATE TABLE IF NOT EXISTS FOLDER_FOLDER (
	FDFD_ref				INTEGER PRIMARY KEY,
	FD_refParent			INTEGER NOT NULL,
	FD_ref 					INTEGER NOT NULL,
	FDFD_creationDate		DATE NOT NULL,
	FDFD_modDate			DATE NOT NULL,
	FOREIGN KEY (FD_refParent) references FOLDER (FD_ref) ON DELETE CASCADE,
	FOREIGN KEY (FD_ref) references FOLDER (FD_ref) ON DELETE CASCADE
);