CREATE TABLE IF NOT EXISTS FOLDER_PAGE (
	FDPG_ref				INTEGER PRIMARY KEY,
	FD_ref 					INTEGER NOT NULL,
	PG_ref 					INTEGER NOT NULL,
	FDPG_creationDate		DATE NOT NULL,
	FDPG_modDate			DATE NOT NULL,
	FOREIGN KEY (FD_ref) references FOLDER (FD_ref) ON DELETE CASCADE,
	FOREIGN KEY (PG_ref) references PAGE (PG_ref) ON DELETE CASCADE
);