CREATE TABLE IF NOT EXISTS FOLDER_DOC (
	FDDOC_REF				INTEGER PRIMARY KEY,
	FD_ref 					INTEGER NOT NULL,
	DOC_ref 					INTEGER NOT NULL,
	FDDOC_creationDate		DATE NOT NULL,
	FDDOC_modDate			DATE NOT NULL,
	FOREIGN KEY (DOC_ref) references DOCUMENT (DOC_ref) ON DELETE CASCADE,
	FOREIGN KEY (FD_ref) references FOLDER (FD_ref) ON DELETE CASCADE
);