name: .NET MAUI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"

jobs:
  Build_Android:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET v9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Install .NET MAUI Workload
        run: |
          dotnet workload install maui

      - name: Restore NuGet
        run: |
          dotnet restore ./src

      - name: Build Android App
        run: |
          dotnet build ./src -f net9.0-android
      - name: Build Windows App
        run: |
          dotnet build ./src
