name: Renovate

on:
  schedule:
    - cron: '0 2 * * 0' 
  workflow_dispatch:   
  repository_dispatch:
    types: [renovate-run]

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.15
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: renovate.json
